
name: Linter
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: v18.0.0
      - run: npm ci
      - name: install
        run: make install
      - name: ESLint test
        run: make lint
